DROP DATABASE IF EXISTS SIMULAEMPRESTIMO;
CREATE DATABASE SIMULAEMPRESTIMO;
USE SIMULAEMPRESTIMO;

CREATE TABLE CLIENTE (
 ID_CLIENTE INT (11) NOT NULL
,NOME VARCHAR (100)
,CPF INT (11) PRIMARY KEY 
,EMAIL VARCHAR(100)

);
CREATE TABLE VEDEDOR (
ID_VENDEDOR INT (11) NOT NULL PRIMARY KEY
,NOME VARCHAR (100)
,CPF INT (11)
,DTNASCIMENTO DATE
,EMAIL VARCHAR (100)
);

CREATE TABLE CONTRATO (
 ID_CONTRATO INT(11) NOT NULL PRIMARY KEY
,VALOR_DO_CONTRATO INT(10)
,NUMERO_PARCELAS INT (12)
);

CREATE TABLE SIMULACAO (
ID_SIMULACAO INT NOT NULL 
,ID_CLIENTE INT NOT NULL
,ID_CONTRATO INT NOT NULL
,ID_VENDEDOR INT NOT NULL
,DATAINICIO DATE
,DATAFINAL DATE
,TXJUROS INT (10)
,QNTPARCERLAS INT (12)
,VALORJUROS INT (12)
,VALORTOTALEMPRESTIMO INT (12)
,PRIMARY KEY (CLIENTE,CONTRATO)
,CONSTRAINT CLINTE FOREIGN KEY (CLIENTE) REFERENCES CLIENTE (CLIENTE,CONTRATO)
,CONSTRAINT CONTRATO FOREIGN KEY (CONTRATO) REFERENCES CONTRATO (ID_CONTRATO)
,CONSTRAINT VENDEDOR FOREIGN KEY (VENDEDOR) REFERENCES VENDEDOR (ID_VENDEDOR)
);
create table vendedores(
Id_vendedores int not null primary key
,login varchar(45)
,senha varchar(45)
,online boolean
);